/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas2plkasir;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ILHAM HADISYAH
 * 
 */
public class kasirApp extends javax.swing.JFrame {

    private int all;

    /**
     * Creates new form kasirApp
     */
   
    public kasirApp() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("App by Ilham Hadisyah");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        addProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        reset = new javax.swing.JButton();
        cashIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonTotal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        messege = new javax.swing.JLabel();
        totalBiaya = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kembali = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(718, 482));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Nama Barang");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 54, 130, 14);

        jLabel2.setText("Harga Satuan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 92, 130, 14);

        jLabel3.setText("Qty");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 130, 70, 14);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(140, 50, 167, 20);

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceKeyTyped(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(140, 90, 166, 20);

        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        jPanel1.add(qty);
        qty.setBounds(140, 130, 70, 20);

        addProduct.setText("In");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });
        jPanel1.add(addProduct);
        addProduct.setBounds(220, 140, 80, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga Satuan", "Qty", "Jumlah harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 676, 124);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(10, 400, 70, 23);

        cashIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashInActionPerformed(evt);
            }
        });
        cashIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashInKeyTyped(evt);
            }
        });
        jPanel1.add(cashIn);
        cashIn.setBounds(520, 340, 165, 20);

        jLabel5.setText("Cash");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 340, 50, 20);

        buttonTotal.setText("total");
        buttonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTotalActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTotal);
        buttonTotal.setBounds(585, 370, 70, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 120, 50, 20);

        jumlah.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jumlah.setText("0");
        jPanel1.add(jumlah);
        jumlah.setBounds(420, 60, 260, 44);
        jPanel1.add(messege);
        messege.setBounds(210, 170, 290, 20);

        totalBiaya.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        totalBiaya.setText("0");
        jPanel1.add(totalBiaya);
        totalBiaya.setBounds(450, 140, 180, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Kembalian :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 400, 70, 14);

        kembali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kembali.setText("0");
        jPanel1.add(kembali);
        kembali.setBounds(390, 390, 200, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText(",00");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(630, 140, 70, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Rp ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 130, 60, 40);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel9.setText("KasirQue");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 0, 180, 40);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTotalActionPerformed
        // TODO add your handling code here:
      
        
        int cash= Integer.parseInt(cashIn.getText());
        int totalBelanja= Integer.parseInt(totalBiaya.getText());
        int kembalian= cash-totalBelanja;
        int invertKembalian = kembalian*(-1);
        if(cash<totalBelanja){
            JOptionPane.showMessageDialog(rootPane, "Cash kurang Rp "+invertKembalian+",00");
           
        }else{
        kembali.setText("Rp "+ kembalian+",00");
        }
        
    }//GEN-LAST:event_buttonTotalActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        // TODO add your handling code here:
        int harga= Integer.parseInt(price.getText());//var harga
        int kuantitas= Integer.parseInt(qty.getText());//var quantity
        int jumlahharga= harga*kuantitas;//var jumlah
        boolean valid=true;
        jumlah.setText(""+jumlahharga);
        jumlah.setVisible(true);
        messege.setText("");
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        if(name.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Maaf anda harus melengkapi seluruh form");
        }
        else{
            Vector z = new Vector();
            z.add(name.getText());
            z.add(price.getText());
            z.add(qty.getText());
            z.add(jumlah.getText());
            tb.addRow(z);
            int total=0;
            for(int e=0;e<tb.getRowCount();e++){
                total +=Integer.parseInt(tb.getValueAt(e, 3).toString());
            }
            
            totalBiaya.setText(""+total);
        }
    }//GEN-LAST:event_addProductActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        tb.removeRow(all);
        totalBiaya.setText("0");
        jumlah.setText("0");
        kembali.setText("0");
    }//GEN-LAST:event_resetActionPerformed

    private void priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_priceKeyTyped

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_qtyKeyTyped

    private void cashInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashInKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_cashInKeyTyped

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void cashInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasirApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasirApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasirApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasirApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasirApp().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton buttonTotal;
    private javax.swing.JTextField cashIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel messege;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qty;
    private javax.swing.JButton reset;
    private javax.swing.JLabel totalBiaya;
    // End of variables declaration//GEN-END:variables
}
